### ISSUE TITLE
Data uploader frontend planning

### ISSUE THREAD

**Issue by knl88** [SeaBee-no/documentation#2]
As developers we need to know the future of `Deb's` data upload application and if there is a wish to use that for uploading metadata. Additionally we need to know:
* What are the issues with this approach from the point of view of other WPs (Kasper expressed some concerns at the Nessodden workshop)?
* How the metadata is stored?
* Does the metadata follow any standard?
* Can it be integrated with geonode (preferably) and/or CloudSQL?

**Comment by JamesSample** [comment]
Notes based on discussion with Kasper (09.06.2022 from 14:30 to 15:00):

- We already use the commercial software [DroneLogbook](https://www.dronelogbook.com/hp/1/index.html) for mission planning. This already captures most of the metadata currently collected by Deb's web frontend
- Use of software such as DroneLogbook for mission planning is mandatory i.e. all drone missions must be entered here before data collection begins
- DroneLogbook provides an [API](https://api.dronelogbook.com/doc/), so rather than entering metadata twice (once in DroneLogbook and then again in Deb's application), it would be better to use the API to take as much metadata as possible directly from DroneLogbook

To do:

1. Identify what metadata we can take from the DroneLogbook API and what additional metadata still needs to be collected separately (e.g. performance stats. from the orthorectification, which are not available at the mission planning stage, or SeaBee-specific metadata such as water optical properties)
2. Modify Deb's web frontend to display a list of available missions/mission IDs from DroneLogbook (I assume each mission in DroneLogbook will have some kind of unique identifier?)
3. In Deb's UI, users should be able to:
    - Select the relevant mission/mission ID from DroneLogbook
    - Add any additional metadata not available from the API if desired (e.g. Secchi depth)
    - Select imagery and supporting files (ground truth data etc.) to be uploaded from their local PC
 
Upon submitting the web form, imagery should be transferred to the MinIO instance on Sigma2 using a consistent file structure and naming conventions. Any metadata not already stored in DroneLogbook should then be added to PostGIS - preferably into Geonode's database, but otherwise into a SeaBee-specific Postgres database running on GCP.

I will mark this planning task as complete and create more specific new tasks based on these notes.
