### ISSUE TITLE
Agree default band order for composite images

### ISSUE THREAD

**Issue by JamesSample** [SeaBee-no/documentation#25]
We need to define a standard band order for SeaBee multiband imagery. This is important, because ML algorithms will expect new data with the same band order as the training data, and we want to avoid having to restack each time.

For traceability, composite images should probably explicitly store the band order in the GeoTiff metadata using `set_band_description` - see e.g. [here ](https://rasterio.readthedocs.io/en/stable/api/rasterio.io.html#rasterio.io.BufferedDatasetWriter.set_band_description) and the example in section 4 [here](https://nbviewer.org/github/JamesSample/image_drone/blob/master/notebooks/frisk_oslofjord_raster_proc.ipynb). However, we should also define a standard band order for SeaBee.

#### RGB only

RGB images should "just work" when added to GIS. This implies `R, G, B = 1, 2, 3`.

#### MS only

For multispec., obvious options are:

- Descending wavelength order: `NIR, RE, R, G, B = 1, 2, 3, 4, 5` (physically sensible, and in the same "direction" as RGB).

- Convenient display order: `R, G, B, NIR, RE = 1, 2, 3, 4, 5` (with this approach, an RGB composite of the MS data will display by default in most GIS applications, but the bands are not ordered by wavelength).

#### Combined RGB and MS

We sometimes combine RGB and multispec. datasets, in which case the bands overlap. Not sure what's best here, but maybe `R, G, B, msNIR, msRE, msR, msG, msB`?

#### Hyperspectral

For hyperspec., I assume the bands are wavelength-ordered, but not sure in which direction (i.e. red to blue or blue to red). Do you have a preference, @jlgarrett ?

___

**Should we just use descending wavelength order (i.e. longest wavelength to shortest) for everything?**

**Comment by jlgarrett** [comment]
Hi James,

For the HSI, the bands are ordered from blue to red. The recommended bands for RGB representations are 94, 57, 19 (644.89, 550.90, 444.89 nm). The descending order in wavelength is more sensible for storage, in my opinion, although the other might be better for display.

-Joe

--

Joseph L. Garrett
Researcher
Norwegian University of Science and Technology
Department of Engineering Cybernetics
________________________________
From: James Sample ***@***.***>
Sent: Wednesday, March 8, 2023 11:33 AM
To: SeaBee-no/documentation ***@***.***>
Cc: Joseph Garrett ***@***.***>; Mention ***@***.***>
Subject: [SeaBee-no/documentation] Agree default band order for composite images (Issue #25)


We need to define a standard band order for SeaBee multiband imagery. This is important, because ML algorithms will expect new data with the same band order as the training data, and we want to avoid having to restack each time.

For traceability, composite images should probably explicitly store the band order in the GeoTiff metadata using set_band_description - see e.g. here <https://rasterio.readthedocs.io/en/stable/api/rasterio.io.html#rasterio.io.BufferedDatasetWriter.set_band_description> and the example in section 4 here<https://nbviewer.org/github/JamesSample/image_drone/blob/master/notebooks/frisk_oslofjord_raster_proc.ipynb>. However, we should also define a standard band order for SeaBee.

RGB only

RGB images should "just work" when added to GIS. This implies R, G, B = 1, 2, 3.

MS only

For multispec., obvious options are:

  *   Descending wavelength order: NIR, RE, R, G, B = 1, 2, 3, 4, 5 (physically sensible, and in the same "direction" as RGB).

  *   Convenient display order: R, G, B, NIR, RE = 1, 2, 3, 4, 5 (with this approach, an RGB composite of the MS data will display by default in most GIS applications, but the bands are not ordered by wavelength).

Combined RGB and MS

We sometimes combine RBG and multispec. datasets, in which case the bands overlap. Not sure what's best here, but maybe R, G, B, msNIR, msRE, msR, msG, msB?

Hyperspectral

For hyperspec., I assume the bands are wavelength-ordered, but not sure in which direction (i.e. red to blue or blue to red). Do you have a preference, @jlgarrett<https://github.com/jlgarrett> ?

________________________________

Should we just use descending wavelength order (i.e. longest wavelength to shortest) for everything?

**Comment by JamesSample** [comment]
I have discussed this via e-mail with several people now, and no-one has a strong preference (but there is general agreement that we need a standard). I'm therefore proposing that:

- SeaBee datasets are stored with bands arranged in **descending order by wavelength** i.e. longest wavelength is band 1 and shortest wavelength is band $n$.

- Wherever possible, the band name (or wavelength interval) should be explicitly stated in the GeoTiff metadata using e.g. [set_band_description](https://rasterio.readthedocs.io/en/stable/api/rasterio.io.html#rasterio.io.BufferedDatasetWriter.set_band_description)

Closing this for now. Feel free to reopen if anyone disagrees strongly :-)
