### ISSUE TITLE
Upgrading GeoNode to latest stable version 

### ISSUE THREAD

**Issue by deviirmr** [SeaBee-no/documentation#45]
In connection with the Seabee annual meeting in 2023 and the suggestion, we are planning to upgrade the current Geonode instance to the latest stable version. @knl88 suggested a new GeoNode instance have security patches which is recommended for the geonode.
@knl88 : I leave it up to you to decide how we proceed on this task, I am available if you want me to test the interface and the functionality. 
@JamesSample

**Comment by knl88** [comment]
This issue is more suitable in the helm-chart repo, and on the geonode fork repo, but there we already have PRs and issues on this, for example [here](https://github.com/SeaBee-no/helm-charts/issues/19). So just closing this for now, this is also one of these things where I hope waiting will mean the geonode team just smooths out potentials problems for us.
