### ISSUE TITLE
NMDC dataset to SeaBee platform

### ISSUE THREAD

**Issue by deviirmr** [SeaBee-no/documentation#47]
In connection with the Seabee annual meeting in 2023 and the suggestions, we decided to expand the Seabee platform by incorporating additional data from various partners. One of the proposed enhancements is the inclusion of the NDMC dataset. However current structure of the NMDC dataset is either unknown or has not been thoroughly explored at this point.
@JamesSample : do you have any updates on this data?  or this is out of focus to Seabee.
@knl88

**Comment by JamesSample** [comment]
This is (very) low priority for now. Probably more suitable for SeaBee2 where we have proposed a Task focusing on integrating SeaBee datasets with other external platforms in order to make SeaBee data more useful/relevant to target user groups. Integration with NMDC could be a good candidate for this, but unlikely to be funded in SeaBee1.

**Comment by deviirmr** [comment]
Thank you for the response @JamesSample 
then we close this issue now and will open during seabee2 if needed.
